version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:latest
    container_name: breedbase_web_sugarcane_training 
    environment:
      PGHOST: db9.sgn.cornell.edu
      PGDATABASE: sandbox_sugarcane_training 
      PGPASSWORD: postgres
      PGUSER: postgres 
    ports:
      - 8119:8080    
    volumes:
      - webdata:/home/production/volume
      # - type: bind
      #   source: /home/production/basesite/empty_db_without.test_users.sql
      #   target: /home/production/empty_dump.sql
      - type: bind
        source: ${HOME}/sugarcane-training.breedbase.org/mason/sugarcane_ai.png
        target: /home/production/cxgn/sugarcane-training.breedbase.org/mason/documents/img/sugarcane_ai.png
      - type: bind
        source: ${HOME}/sugarcane-training.breedbase.org/mason
        target: /home/production/cxgn/sugarcane-training.breedbase.org/mason
      - type: bind
        source: /home/production/sgn_local_confs/sugarcane_training/sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: /home/production/db_dumps
        target: /db_dumps
      - type: bind
        source: /home/production/basesite/crontab
        target: /etc/crontab
      - type: bind
        source: bash_history
        target: /home/production/.bash_history
volumes:
  webdata:



