version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:latest
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 8080:8080
    volumes:
      - webdata:/home/production/volume
      # - type: bind
      #   source: /home/production/basesite/empty_db_without.test_users.sql
      #   target: /home/production/empty_dump.sql
      - type: bind
        source: ${HOME}/Documents/cxgn/sugarcane-training.breedbase.org/mason
        target: /home/production/cxgn/sugarcane-training.breedbase.org/mason
      - type: bind
        source: /home/production/home/production/sugarcane-training.breedbase.org/sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: /home/production/db_dumps
        target: /db_dumps
      - type: bind
        source: /home/production/basesite/crontab
        target: /etc/crontab
      - type: bind
        source: bash_history
        target: /home/production/.bash_history
    environment:
      - TZ=America/New_York
volumes:
  webdata:



