version: "3.7"

services:
  breedbase:
    image: breedbase/breedbase:latest
    container_name: breedbase_web_sugarcane_training
    ports:
      - 8119:8080
    volumes:
      - webdata:/home/production/volume
      - type: bind
        source: /home/production/sugarcane-training.breedbase.org/empty_db_without.test_users.sql
        target: /home/production/empty_dump.sql
#      - type: bind
#        source: /home/production/sgn
#        target: /home/production/cxgn/sgn
      - type: bind
        source: /home/production/sugarcane-training.breedbase.org/sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: /home/production/db_dumps
        target: /db_dumps
      - type: bind
        source: /home/production/sugarcane-training.breedbase.org/crontab
        target: /etc/crontab
      - type: bind
        source: bash_history
        target: /home/production/.bash_history

volumes:
  webdata:



